use_frameworks!

platform :ios, '10.0'

target 'SwiftUIVerticalPageView_Example' do
  pod 'SwiftUIVerticalPageView', :path => '../'

  target 'SwiftUIVerticalPageView_Tests' do
    inherit! :search_paths

    
  end
end
